# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/rpidemo/rpi-mmal-demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/rpidemo/rpi-mmal-demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/rpidemo/rpi-mmal-demo/CMakeFiles /home/pi/rpidemo/rpi-mmal-demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/rpidemo/rpi-mmal-demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SAM_demo

# Build rule for target.
SAM_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SAM_demo
.PHONY : SAM_demo

# fast build rule for target.
SAM_demo/fast:
	$(MAKE) -f CMakeFiles/SAM_demo.dir/build.make CMakeFiles/SAM_demo.dir/build
.PHONY : SAM_demo/fast

#=============================================================================
# Target rules for targets named SAM_rec

# Build rule for target.
SAM_rec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SAM_rec
.PHONY : SAM_rec

# fast build rule for target.
SAM_rec/fast:
	$(MAKE) -f CMakeFiles/SAM_rec.dir/build.make CMakeFiles/SAM_rec.dir/build
.PHONY : SAM_rec/fast

SAM_demo.o: SAM_demo.c.o
.PHONY : SAM_demo.o

# target to build an object file
SAM_demo.c.o:
	$(MAKE) -f CMakeFiles/SAM_demo.dir/build.make CMakeFiles/SAM_demo.dir/SAM_demo.c.o
.PHONY : SAM_demo.c.o

SAM_demo.i: SAM_demo.c.i
.PHONY : SAM_demo.i

# target to preprocess a source file
SAM_demo.c.i:
	$(MAKE) -f CMakeFiles/SAM_demo.dir/build.make CMakeFiles/SAM_demo.dir/SAM_demo.c.i
.PHONY : SAM_demo.c.i

SAM_demo.s: SAM_demo.c.s
.PHONY : SAM_demo.s

# target to generate assembly for a file
SAM_demo.c.s:
	$(MAKE) -f CMakeFiles/SAM_demo.dir/build.make CMakeFiles/SAM_demo.dir/SAM_demo.c.s
.PHONY : SAM_demo.c.s

SAM_rec.o: SAM_rec.c.o
.PHONY : SAM_rec.o

# target to build an object file
SAM_rec.c.o:
	$(MAKE) -f CMakeFiles/SAM_rec.dir/build.make CMakeFiles/SAM_rec.dir/SAM_rec.c.o
.PHONY : SAM_rec.c.o

SAM_rec.i: SAM_rec.c.i
.PHONY : SAM_rec.i

# target to preprocess a source file
SAM_rec.c.i:
	$(MAKE) -f CMakeFiles/SAM_rec.dir/build.make CMakeFiles/SAM_rec.dir/SAM_rec.c.i
.PHONY : SAM_rec.c.i

SAM_rec.s: SAM_rec.c.s
.PHONY : SAM_rec.s

# target to generate assembly for a file
SAM_rec.c.s:
	$(MAKE) -f CMakeFiles/SAM_rec.dir/build.make CMakeFiles/SAM_rec.dir/SAM_rec.c.s
.PHONY : SAM_rec.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... SAM_demo"
	@echo "... SAM_rec"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SAM_demo.o"
	@echo "... SAM_demo.i"
	@echo "... SAM_demo.s"
	@echo "... SAM_rec.o"
	@echo "... SAM_rec.i"
	@echo "... SAM_rec.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

